CREATE TABLE `inspectionReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`adminId` int NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`clientAddress` text NOT NULL,
	`inspectionDate` timestamp NOT NULL,
	`recalqueTubulacao` varchar(50),
	`recalqueAcionamento` varchar(50),
	`recalqueBoias` varchar(50),
	`recalqueLimpezaPainel` varchar(50),
	`recalqueLimpezaSala` varchar(50),
	`recalqueTensaoPainel` varchar(50),
	`recalqueCorrenteR` varchar(50),
	`recalqueCorrenteS` varchar(50),
	`recalqueCorrenteT` varchar(50),
	`recalqueRuido` varchar(50),
	`drenoTubulacao` varchar(50),
	`drenoAcionamento` varchar(50),
	`drenoBoias` varchar(50),
	`drenoLimpezaPainel` varchar(50),
	`drenoTensaoPainel` varchar(50),
	`drenoCorrenteL1` varchar(50),
	`drenoCorrenteL2` varchar(50),
	`drenoRuido` varchar(50),
	`piscinaTubulacao` varchar(50),
	`piscinaAcionamento` varchar(50),
	`piscinaBoias` varchar(50),
	`piscinaLimpezaPainel` varchar(50),
	`piscinaTensaoPainel` varchar(50),
	`piscinaCorrenteR` varchar(50),
	`piscinaCorrenteS` varchar(50),
	`piscinaCorrenteT` varchar(50),
	`incendioB1Tubulacao` varchar(50),
	`incendioB1Acionamento` varchar(50),
	`incendioB1LimpezaSala` varchar(50),
	`incendioB1LimpezaPainel` varchar(50),
	`incendioB1TensaoPainel` varchar(50),
	`incendioB1Corrente` varchar(50),
	`incendioB1Ruido` varchar(50),
	`incendioB2Tubulacao` varchar(50),
	`incendioB2Acionamento` varchar(50),
	`incendioB2LimpezaSala` varchar(50),
	`incendioB2LimpezaPainel` varchar(50),
	`incendioB2TensaoPainel` varchar(50),
	`incendioB2Corrente` varchar(50),
	`incendioB2Ruido` varchar(50),
	`observations` text,
	`technicianSignature` text,
	`clientSignature` text,
	`photos` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `inspectionReports_id` PRIMARY KEY(`id`)
);
